spring:
  application:
    name: recipe-explorer
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/recipe_explorer?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    #    auto-detected this is default option
#    database-platform: org.hibernate.dialect.MySQLDialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true # to allow hibernate table definition first, than populate tables script based
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:
logging:
  level:
    web: debug

server:
  port: 8080

comments:
  api:
    baseUrl: "http://localhost:8081/api/comments/"


